export const ErrorsList = {
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  SESSION_NOT_SET: 'SESSION_NOT_SET',
  SESSION_ALREADY_CLOSED: 'SESSION_ALREADY_CLOSED',
  SESSION_DO_NOT_EXIST_OR_CLOSED: 'SESSION_DO_NOT_EXIST_OR_CLOSED',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
};

// export default ErrorsList;
