export const ErrorsList = {
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  SESSION_NOT_SET: 'SESSION_NOT_SET',
  SESSION_ALREADY_CLOSED: 'SESSION_ALREADY_CLOSED',
  SESSION_DO_NOT_EXIST_OR_CLOSED: 'SESSION_DO_NOT_EXIST_OR_CLOSED',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  INVALID_EMAIL: 'INVALID_EMAIL',
  USER_REGISTER_ERROR: 'USER_REGISTER_ERROR',
  FOLLOWING_OPERATION_ERROR: 'FOLLOWING_OPERATION_ERROR',
  USER_MODIFYING_ERROR: 'USER_MODIFYING_ERROR',
};

// export default ErrorsList;
